import type { Metadata } from "next";
import { Noto_Sans_Mono, Noto_Sans_Ol_Chiki} from "next/font/google";
import "./globals.css";
import React from "react";
import Navbar from "@/app/blog-project/ui/navbar";
import Footer from "@/app/blog-project/ui/footer";

const notoSansOlChiki = Noto_Sans_Ol_Chiki({
    variable: "--font-sans",
    subsets: ["latin"],
});

const notoSansMono = Noto_Sans_Mono({
    variable: "--font-mono",
    subsets: ["latin"],
});


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }:{children: React.ReactNode} ) {
    return (
        <html
            lang="en"
            className={`${notoSansOlChiki.variable} ${notoSansMono.variable} h-full antialiased`}
        >
        <body className="bg-[#1a1a1a] min-h-screen flex flex-col">
        <Navbar/>
        <main className="flex-1">{children}</main>
        <Footer />
        </body>
        </html>
    );
}
